'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { ArrowRight, ArrowUpRight, Search, X, Clock3, Code2, Check, Bookmark, Sunrise, Sunset } from 'lucide-react';
import type { Story } from '@/lib/data';
import { appConfig } from '@/lib/env';
import { getBackend, PAGE_SIZE } from '@/lib/backend';
import { Art, BookmarkButton, DemoNote, SectionTitle, StoryCard } from './shared';
import { useDemo } from './state';
export function Newsroom({ developer = false }: { developer?: boolean }) {
 const [query, setQuery] = useState(''); const [filter, setFilter] = useState('ทั้งหมด'); const [saved, setSaved] = useState(false); const [edition, setEdition] = useState('เช้า');
 const mock = appConfig.source === 'mock';
 const [stories, setStories] = useState<Story[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
 const [offset, setOffset] = useState(0); const [refresh, setRefresh] = useState(0);
 useEffect(() => {
  let active = true; setLoading(true); setError(false);
  const timer = setTimeout(() => {
   getBackend().list(mock ? '' : query, offset).then(data => { if(active) setStories(data); })
    .catch(() => {if(active) setError(true);}).finally(() => {if(active) setLoading(false);});
  }, mock ? 0 : 250);
  return () => {active=false;clearTimeout(timer);};
 }, [mock, query, offset, refresh]);
 const { bookmarks } = useDemo();
 const params = useSearchParams();
 useEffect(() => { setSaved(params.get('saved') === '1'); if (params.has('search')) document.getElementById('news-search')?.focus(); }, [params]);
 const categories = developer ? ['ทั้งหมด', 'TypeScript', 'Next.js', 'Python', 'Tools', 'Releases', 'Workflow'] : ['ทั้งหมด', 'โลก AI', 'เครื่องมือ', 'งานวิจัย', 'มุมมอง', 'Workflow'];
 const filtered = stories.filter(s => (!developer || s.technical) && (filter === 'ทั้งหมด' || s.category === filter || s.tags.includes(filter)) && (!saved || bookmarks.includes(s.id)) && `${s.title} ${s.summary} ${s.tags.join(' ')} ${s.source}`.toLowerCase().includes(query.trim().toLowerCase()));
 const filtering = query.trim() || filter !== 'ทั้งหมด' || saved;
 const editionStories = stories.filter(s => !developer || s.technical);
 const lead = mock && developer ? stories[2] : editionStories[0];
 return <main id="main" className="shell newsroom"><div className="issue-line"><div><span className="blue-dot"/>THE {developer ? 'DEVELOPER' : 'DAILY'} EDITION <span className="issue-divider">/</span> {developer ? 'อ่านให้รู้ แล้วลงมือสร้าง' : 'เรื่องสำคัญของ AI ในวันที่โลกไม่หยุดเปลี่ยน'}</div><span className="issue-status"><Clock3 size={13}/> {mock ? 'รอบตัวอย่าง 07:00 น. · Asia/Bangkok' : 'ยังไม่เปิดรอบอัตโนมัติ · Asia/Bangkok'}</span></div>
 <div className="page-intro"><div><span className="eyebrow">{developer ? 'FOR THE BUILDERS' : 'A LITTLE CLARITY, EVERY DAY.'}</span><h1>{developer ? <>อัปเดตให้ทัน<span className="blue"> สร้างให้ดีกว่าเดิม</span></> : <>โลก AI วันนี้<span className="blue"> มีอะไรน่ารู้</span></>}</h1><p>{developer ? 'เครื่องมือ แนวปฏิบัติ และมุมมองที่ช่วยให้การพัฒนามีทิศทาง' : 'คัดเรื่องสำคัญ ย่อยให้เข้าใจ เชื่อมเทคโนโลยีเข้ากับชีวิตและการทำงาน'}</p></div>{mock && <div className="tabs tabs-box edition-tabs" aria-label="เลือกฉบับตัวอย่าง"><button aria-pressed={edition === 'เช้า'} className={`tab ${edition === 'เช้า' ? 'tab-active selected' : ''}`} onClick={() => setEdition('เช้า')}><Sunrise size={16}/> ฉบับเช้า</button><button aria-pressed={edition === 'เย็น'} className={`tab ${edition === 'เย็น' ? 'tab-active selected' : ''}`} onClick={() => setEdition('เย็น')}><Sunset size={16}/> ฉบับเย็น</button></div>}</div>
 <div className="filterbar"><div className="filter-chips">{categories.map(c => <button className={`btn btn-ghost btn-sm ${filter === c ? 'btn-neutral selected' : ''}`} aria-pressed={filter === c} key={c} onClick={() => setFilter(c)}>{c}</button>)}</div><div className="search-group"><label className="input input-bordered input-sm searchbox"><Search size={16}/><input id="news-search" aria-label="ค้นหาข่าว" value={query} maxLength={200} onChange={e => {setQuery(e.target.value);setOffset(0);}} placeholder={developer ? 'ค้นหาข่าว หรือ stack...' : 'ค้นหาเรื่องที่สนใจ...'}/>{query && <button className="btn btn-ghost btn-circle btn-xs" onClick={() => setQuery('')} aria-label="ล้างการค้นหา"><X size={14}/></button>}</label><button className={`btn btn-ghost btn-square btn-sm icon-button ${saved ? 'saved' : ''}`} aria-label="กรองรายการอ่านภายหลัง" aria-pressed={saved} onClick={() => setSaved(!saved)}><Bookmark size={18}/></button></div></div>
 {!mock && <div className="flex flex-wrap items-center gap-3 py-3"><span>ข่าวที่เผยแพร่ · ตัวกรองหมวดและรายการอ่านภายหลังใช้กับข่าวในหน้านี้</span><button className="btn btn-outline btn-sm" onClick={()=>setRefresh(x=>x+1)} disabled={loading}>โหลดข่าวใหม่</button></div>}
 {error && <p role="alert" className="alert alert-warning">โหลดข้อมูลรอบใหม่ไม่สำเร็จ{stories.length ? ' · กำลังแสดงผลที่โหลดสำเร็จก่อนหน้า' : ''}</p>}
 {loading ? <div className="empty-state" role="status">กำลังโหลดข่าว…</div> : !stories.length && !filtering ? <div className="empty-state"><h2>{error ? 'ยังโหลดข่าวไม่ได้' : 'ยังไม่มีข่าวเผยแพร่'}</h2><p>ไม่มีข้อมูลจำลองมาแทนผลจาก Supabase</p></div> : edition === 'เย็น' ? <div className="empty-state"><Sunset size={36}/><h2>ฉบับเย็นยังไม่พร้อมในตัวอย่างนี้</h2><p>เวลาเริ่มรอบตามแผน 19:00 น. Asia/Bangkok · cron ยังไม่เปิดใช้งาน</p><button className="btn btn-primary btn-sm primary-button" onClick={() => setEdition('เช้า')}>กลับไปอ่านฉบับเช้า</button></div> : filtering || !lead ? <section className="search-results"><SectionTitle title={`${saved ? 'รายการอ่านภายหลัง' : 'ผลการค้นหา'} · ${filtered.length} เรื่อง`}/>{filtered.length ? <div className="cards-grid">{filtered.map(s => <StoryCard key={s.id} story={s}/>)}</div> : <div className="empty-state"><Search size={32}/><h2>ยังไม่พบเรื่องที่ตรงกัน</h2><p>ลองเปลี่ยนคำค้นหรือเลือกหมวดอื่น</p><button className="btn btn-outline btn-sm plain-button" onClick={() => {setQuery(''); setFilter('ทั้งหมด'); setSaved(false);}}>ล้างตัวกรอง</button></div>}</section> : <>
 <section className="front-grid"><article className="lead-story"><Link href={lead.href ?? `/news/${lead.id}`} className="lead-art"><Art kind={lead.art}/><span className="image-label">ภาพประกอบแนวคิด{mock ? ' · ข้อมูลจำลอง' : ''}</span></Link><div className="story-kicker"><span className="filled-label">{developer ? 'DEVELOPER FOCUS' : 'เรื่องเด่นประจำวัน'}</span>{lead.category} <span>/ {lead.type}</span></div><h2><Link href={lead.href ?? `/news/${lead.id}`}>{lead.title}</Link></h2><p>{lead.summary}</p><div className="story-meta"><span>{lead.source} <span className="meta-dot">·</span> อ่าน {lead.read} นาที</span><div><BookmarkButton id={lead.id}/><Link className="read-link" href={lead.href ?? `/news/${lead.id}`}>อ่านต่อ <ArrowUpRight size={16}/></Link></div></div></article>
 <div className="secondary-column">{(mock ? (developer ? [stories[5], stories[1]] : [stories[1], stories[2]]) : editionStories.slice(1,3)).map(s => <StoryCard key={s.id} story={s}/>)}</div>
 <aside className="right-column"><SectionTitle eyebrow="THE BRIEF" title="อ่านโลก AI ใน 5 นาที"/><p className="muted">เริ่มวันด้วย 3 ประเด็นที่ควรเข้าใจ<br/>{mock ? 'จากโต๊ะข่าวจำลองของเรา' : 'จากข่าวที่ผ่านการอนุมัติ'}</p><ol className="brief-list">{(mock ? (developer ? [stories[2], stories[4], stories[5]] : [stories[0], stories[1], stories[3]]) : editionStories.slice(0,3)).map((s, i) => <li key={s.id}><span>0{i+1}</span><Link href={s.href ?? `/news/${s.id}`}>{s.title}<ArrowUpRight size={13}/></Link></li>)}</ol><div className="editor-note"><span className="eyebrow">EDITOR’S NOTE</span><span className="quote-mark">“</span><h3>ตามเทคโนโลยีให้ทัน<br/>โดยไม่ต้องตามทุกเรื่อง</h3><p>เราเชื่อว่าข่าวที่ดีควรช่วยให้คุณเข้าใจ และตัดสินใจได้ว่าจะทำอะไรต่อ</p><span className="editor-sign">— โต๊ะบรรณาธิการ AI Daily</span></div><div className="schedule-note"><span className="blue-dot"/><div><strong>{mock ? 'สองฉบับ ในทุกวัน' : 'รอบตามแผน'}</strong><p>07:00 / 19:00 · เวลาไทย</p><small>{mock ? 'ตารางตัวอย่าง · ยังไม่มี cron จริง' : 'ยังไม่เปิด scheduler'}</small></div></div></aside></section>
 {mock && <DemoNote/>}
 {mock && developer && <section id="radar" className="radar-section"><SectionTitle eyebrow="TOOLS & FRAMEWORKS" title="อยู่ในเรดาร์นักพัฒนา"/><div className="radar-grid"><div className="radar-card"><div className="tool-icon"><Code2/></div><div><h3>Context Kit <span className="badge badge-outline badge-sm pill">ติดตาม</span></h3><p>จัดชุดไฟล์ให้มีบริบทพอดี · TypeScript / Next.js</p><small>เครื่องมือสมมติ · 0.4-demo · ราคาไม่ระบุ</small></div><Link href="/news/context-kit" aria-label="อ่าน Context Kit"><ArrowUpRight/></Link></div><div className="radar-card"><div className="tool-icon">fb</div><div><h3>Flowbase <span className="badge badge-outline badge-sm pill">ติดตาม</span></h3><p>อ่านสัญญา API ก่อนย้ายเวอร์ชัน · Python</p><small>เครื่องมือสมมติ · 2.0-demo · ยังไม่ประเมิน</small></div><Link href="/news/release-radar" aria-label="อ่าน Flowbase"><ArrowUpRight/></Link></div></div></section>}
 <section className="latest-section"><SectionTitle eyebrow={developer ? 'ENGINEERING NOTES' : 'WORTH YOUR ATTENTION'} title={developer ? 'อ่านก่อนลงมือ' : 'เรื่องอื่นที่ไม่อยากให้พลาด'}/><div className="cards-grid">{(mock ? (developer ? [stories[0], stories[4], stories[5]] : [stories[3], stories[4], stories[5]]) : editionStories.slice(3)).map(s => <StoryCard key={s.id} story={s}/>)}</div></section>
 {mock && <section id="playbook" className="playbook-banner"><div className="playbook-symbol">↗</div><div><span className="eyebrow">THE WORKFLOW PLAYBOOK</span><h2>น้อยขั้นตอนลง ชัดเจนขึ้น</h2><p>เริ่มต้นจากโจทย์ ใช้ของเดิมเมื่อเหมาะสม และตรวจสิ่งที่สำคัญ</p></div><Link href="/news/feature-playbook" className="btn btn-neutral btn-sm dark-button">เปิด Playbook <ArrowRight size={18}/></Link></section>}
 <div className="trust-line"><span><Check size={16}/> แยกข่าวกับความคิดเห็น</span><span><Check size={16}/> อ่านจากข้อเท็จจริงชุดเดียวกัน</span><span><Check size={16}/> ไม่แต่งผลการทดลอง</span></div>
 </>}
 {!mock && <div className="flex gap-3 py-6"><button className="btn btn-outline" disabled={loading||offset===0} onClick={()=>setOffset(x=>Math.max(0,x-PAGE_SIZE))}>หน้าก่อน</button><button className="btn btn-outline" disabled={loading||stories.length<PAGE_SIZE} onClick={()=>setOffset(x=>x+PAGE_SIZE)}>หน้าถัดไป</button></div>}
 </main>;
}
