'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ArrowUpRight, Bookmark, Code2, ArrowRight, Search, SlidersHorizontal, Sun, Newspaper, CircleHelp } from 'lucide-react';
import { useDemo } from './state';
import { appConfig } from '@/lib/env';
import type { Story } from '@/lib/data';
export function Header() {
 const pathname = usePathname(); const admin = pathname.startsWith('/admin');
 return <><div className="prototype"><span className="demo-dot" /> {appConfig.source === 'mock' ? 'PROTOTYPE' : 'AI DAILY'} <span className="prototype-separator">/</span> {appConfig.source === 'mock' ? 'ข่าว สถานะระบบ และค่าใช้จ่ายทั้งหมดเป็นข้อมูลจำลอง' : 'โหมด Supabase · AI และ scheduler ยังไม่เปิดใช้งาน'}</div><header className="site-header shell"><div className="masthead"><div className="edition"><span>{appConfig.source === 'mock' ? 'วันอาทิตย์ที่ 20 กันยายน 2569' : 'ข่าว AI ภาษาไทย'}</span><span><Sun size={14} /> {appConfig.source === 'mock' ? 'ฉบับเช้า · ฉบับตัวอย่าง 001' : 'ข่าวที่ผ่านการอนุมัติ'}</span></div><Link href="/" className="wordmark" aria-label="AI Daily หน้าแรก">AI<span>DAILY</span><i>.</i></Link><div className="masthead-right"><span>เข้าใจ AI ทุกวัน</span><Link href="/admin">โต๊ะบรรณาธิการ <ArrowUpRight size={14}/></Link></div></div><nav className="main-nav" aria-label="เมนูหลัก"><div className="view-switch"><Link className={!admin && !pathname.startsWith('/developers') ? 'active' : ''} href="/"><Newspaper size={16}/> ข่าว AI</Link><Link className={pathname.startsWith('/developers') ? 'active' : ''} href="/developers"><Code2 size={17}/> สำหรับนักพัฒนา</Link></div><div className="nav-secondary"><Link href="/developers#radar">Tools Radar</Link><Link href="/developers#playbook">Workflow</Link><Link href="/?saved=1" aria-label="รายการอ่านภายหลัง"><Bookmark size={17}/></Link><Link href="/?search=1" aria-label="ค้นหาข่าว"><Search size={18}/></Link><Link className={admin ? 'active' : ''} href="/admin" aria-label="หลังบ้าน"><SlidersHorizontal size={17}/></Link></div></nav></header></>;
}
export function Footer() { return <footer className="shell footer"><div><Link href="/" className="footer-brand">AI DAILY.</Link><p>ข่าวที่ช่วยให้เข้าใจ เทคโนโลยีที่ช่วยให้ลงมือ</p></div><div><span>สร้างพื้นที่ให้ความรู้ มากกว่าความตื่นเต้น</span><small>{appConfig.source === 'mock' ? 'UI Prototype · ไม่มี AI API หรือ cron ทำงานจริง' : 'AI API และ cron ยังไม่เปิดใช้งาน'}</small></div></footer>; }
export function SectionTitle({ eyebrow, title, href, label = 'ดูทั้งหมด' }: { eyebrow?: string; title: string; href?: string; label?: string }) { return <div className="section-heading"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{href && <Link href={href}>{label}<ArrowRight size={16}/></Link>}</div>; }
export function BookmarkButton({ id }: { id: string }) { const { bookmarks, bookmark } = useDemo(); const saved = bookmarks.includes(id); return <button className={`btn btn-ghost btn-square btn-sm icon-button ${saved ? 'saved' : ''}`} aria-label={saved ? 'นำออกจากรายการอ่านภายหลัง' : 'บันทึกอ่านภายหลัง'} aria-pressed={saved} onClick={() => bookmark(id)}><Bookmark size={18} fill={saved ? 'currentColor' : 'none'}/></button>; }
export function Art({ kind, small = false }: { kind: string; small?: boolean }) { return <div className={`art art-${kind} ${small ? 'art-small' : ''}`} aria-hidden="true"><div className="art-grid"/>{kind === 'orbit' ? <><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-ring ring-three"/><div className="agent-core">a<span>i</span><i>✳</i></div><div className="floating-note note-one"><span className="note-dot"/>RESEARCH<span>ค้นหา → เข้าใจ</span></div><div className="floating-note note-two"><Code2 size={18}/> BUILD<span>จากแนวคิดสู่ลงมือ</span></div><div className="floating-note note-three">✓<span>HUMAN IN THE LOOP</span></div><span className="art-corner">THE NEXT CHAPTER OF AI</span></> : <><div className="abstract-shape"><span>{kind === 'model' ? 'm' : kind === 'context' ? '{ }' : kind === 'workflow' ? '↗' : kind === 'release' ? '2.0' : '“'}</span></div><span className="art-corner">{kind === 'model' ? 'SMALLER. FOCUSED.' : kind === 'context' ? 'LESS CONTEXT. MORE CLARITY.' : kind === 'workflow' ? 'BUILD WITH INTENTION' : kind === 'release' ? 'RELEASE NOTES' : 'THE HUMAN PERSPECTIVE'}</span></>}</div>; }
export function StoryCard({ story, image = true }: { story: Story; image?: boolean }) { return <article className="story-card">{image && <Link href={story.href ?? `/news/${story.id}`} tabIndex={-1}><Art kind={story.art} small/></Link>}<div className="story-kicker">{story.category}<span>· {story.type}</span></div><h3><Link href={story.href ?? `/news/${story.id}`}>{story.title}</Link></h3><p>{story.summary}</p><div className="story-meta"><span>{story.source} · {story.read} นาที</span><BookmarkButton id={story.id}/></div></article>; }
export function DemoNote({ children }: { children?: React.ReactNode }) { return <div role="note" className="alert alert-soft demo-note"><CircleHelp size={16}/><span>{children || 'เนื้อหาสมมติสำหรับทดลองหน้าจอ ไม่ใช่ข่าวที่ผ่านการตรวจสอบหรือผลทดลองจริง'}</span></div>; }
export function AdminNav() { const path = usePathname().replace(/\/$/, '') || '/'; return <nav className="tabs admin-nav" aria-label="เมนูหลังบ้าน">{[['/admin', 'คัดข่าว'], ['/admin/settings', 'Agents & Providers'], ['/admin/usage', 'Usage & Budget']].map(([href, name]) => <Link href={href} key={href} aria-current={path === href ? 'page' : undefined} className={`tab ${path === href ? 'tab-active active' : ''}`}>{name}</Link>)}<span>{appConfig.source === 'mock' ? 'Sandbox workspace' : 'Supabase workspace'}</span></nav>; }
