export type Story = {
  id: string; title: string; summary: string; category: string; type: string;
  source: string; time: string; read: number; tags: string[]; art: string;
  href?: string; publishedAt?: string; updatedAt?: string; citations?: { label: string; url: string; source_published_at: string | null }[];
  why: string; audience: string; technical?: { impact: string; steps: string[]; caveat: string };
};
export const stories: Story[] = [
  { id: 'agent-workspace', title: 'เมื่อ AI ไม่ได้แค่ตอบคำถาม แต่เริ่มช่วยเราทำงานจนเสร็จ', summary: 'สำรวจแนวคิด Agent workspace ผ่านสถานการณ์สมมติ: จากผู้ช่วยในช่องแชต สู่การวางแผน ค้นข้อมูล และส่งงานให้มนุษย์ตรวจในพื้นที่เดียว', category: 'โลก AI', type: 'ข่าว', source: 'AI Daily Demo Lab', time: '06:45', read: 5, tags: ['AI Agents', 'TypeScript'], art: 'orbit', why: 'จุดที่น่าจับตาคือการออกแบบขั้นตอนให้ตรวจสอบได้ คนยังต้องกำหนดขอบเขตและอนุมัติสิ่งที่มีผลจริง', audience: 'คนทำงานความรู้ ทีมผลิตภัณฑ์ และนักพัฒนาที่กำลังออกแบบผู้ช่วย AI', technical: { impact: 'ตัวอย่างนี้แบ่งงานเป็น plan → draft → review พร้อมเก็บสถานะงานให้ตรวจย้อนหลังได้ โดยยังไม่มีการเชื่อมเครื่องมือจริง', steps: ['กำหนดขอบเขตงานและเงื่อนไขความสำเร็จก่อนเริ่ม', 'สร้างร่างในพื้นที่ทดลองและแสดงรายการเปลี่ยนแปลง', 'ให้ผู้ใช้ตรวจผลก่อนอนุญาตให้เกิดผลภายนอก'], caveat: 'เป็นแนวคิดจำลอง ไม่มี benchmark หรือผลทดลองยืนยันการลดเวลาและต้นทุน' } },
  { id: 'small-model', title: 'โมเดลเล็ก งานเฉพาะทาง: ทางเลือกที่ควรเริ่มจากโจทย์', summary: 'ถ้าไม่ได้ต้องการคำตอบทุกเรื่อง เราจะออกแบบการเลือกโมเดลให้เหมาะกับงานได้อย่างไร', category: 'งานวิจัย', type: 'งานวิจัย', source: 'Research Desk · สมมติ', time: '06:30', read: 4, tags: ['Python', 'Models'], art: 'model', why: 'การเลือกจากขนาดอย่างเดียวไม่พอ ควรตรวจคุณภาพ ความหน่วง และต้นทุนบนชุดงานเดียวกัน', audience: 'ทีมที่ต้องการเปรียบเทียบโมเดลก่อนเลือกใช้', technical: { impact: 'เริ่มด้วย evaluation set ที่มีกรณีปกติและกรณีล้มเหลว แล้วเปรียบเทียบด้วยเกณฑ์เดียวกัน', steps: ['เตรียมตัวอย่างงานและผลที่ยอมรับได้', 'รันโมเดลแต่ละตัวด้วยข้อกำหนดเดียวกัน', 'อ่าน error และคำนวณต้นทุนรวม retry'], caveat: 'บทความจำลอง ไม่มีตัวเลขประสิทธิภาพจากงานวิจัยจริง' } },
  { id: 'context-kit', title: 'Context Kit: จัดบริบทให้พอดี ก่อนส่งงานให้ AI', summary: 'เครื่องมือสมมติสำหรับเลือกเฉพาะไฟล์ที่เกี่ยวข้อง ลดข้อมูลส่วนเกินโดยไม่ทำข้อกำหนดสำคัญหายไป', category: 'เครื่องมือ', type: 'ประกาศบริษัท', source: 'Context Kit · สมมติ', time: '06:10', read: 3, tags: ['TypeScript', 'Next.js', 'Tools'], art: 'context', why: 'การส่งข้อมูลที่เกี่ยวข้องช่วยให้ทีมตรวจสอบได้ว่าโมเดลใช้ข้อกำหนดชุดใด แต่ยังต้องวัดผลกับงานจริง', audience: 'AI Fullstack Developer และทีมที่ใช้ coding assistant', technical: { impact: 'ตัวอย่าง release 0.4-demo เปลี่ยนชื่อ includePaths เป็น files; เป็นสัญญา API สมมติสำหรับทดลองอ่าน breaking change', steps: ['สร้าง branch ทดลองและเลือกไฟล์ที่จำเป็น', 'ตรวจรายการ files และไม่รวม secrets', 'รัน typecheck และทดสอบงานเดิมก่อนนำไปใช้'], caveat: 'เครื่องมือนี้ไม่มีอยู่จริง ไม่มีแพ็กเกจให้ติดตั้ง และยังไม่ได้วัดผล' } },
  { id: 'human-review', title: 'งานไหนควรให้ AI ช่วย และงานไหนควรให้คนตัดสินใจ', summary: 'มุมมองบรรณาธิการจำลองต่อการวางจุดตรวจของมนุษย์ในงานที่มีผลกระทบ', category: 'มุมมอง', type: 'ความคิดเห็น', source: 'โต๊ะบรรณาธิการ · สมมติ', time: '05:55', read: 4, tags: ['AI Agents', 'แนวคิด'], art: 'human', why: 'การอนุมัติที่มีความหมายต้องทำให้ผู้ใช้เห็นทั้งผลลัพธ์ ข้อจำกัด และสิ่งที่จะเกิดขึ้นต่อ', audience: 'ทุกคนที่นำ AI มาใช้ในงานประจำ' },
  { id: 'feature-playbook', title: 'เริ่มจากเกณฑ์สำเร็จ ก่อนเริ่มเขียนโค้ด', summary: 'Playbook 4 ขั้นตอนสำหรับเพิ่ม feature ให้ขอบเขตชัด ใช้ของเดิมซ้ำ และตรวจพฤติกรรมที่สำคัญ', category: 'Workflow', type: 'แนวปฏิบัติ', source: 'Engineering Desk · สมมติ', time: '05:40', read: 6, tags: ['TypeScript', 'Next.js', 'Workflow'], art: 'workflow', why: 'เกณฑ์สำเร็จช่วยให้คนและ AI เห็นเป้าหมายเดียวกัน และรู้ว่าควรหยุดเพิ่มความซับซ้อนเมื่อใด', audience: 'นักพัฒนา frontend, backend และ AI engineering', technical: { impact: 'สิ่งที่ต้องเตรียม: repository ทดลอง พฤติกรรมที่คาดหวัง และคำสั่งตรวจโค้ดของโปรเจกต์', steps: ['เขียนตัวอย่าง input และพฤติกรรมที่ยอมรับได้', 'อ่านรูปแบบเดิมและค้นหาส่วนที่ใช้ซ้ำได้', 'แก้เฉพาะเส้นทางที่จำเป็นต่อเป้าหมาย', 'ตรวจ typecheck และเส้นทางใช้งานจริงกับเกณฑ์ที่ตั้งไว้'], caveat: 'ผลที่คาดหวังคือขอบเขตที่ตรวจได้ ไม่ใช่การรับประกันว่าจะใช้เวลาน้อยลง; ระวังการทดสอบที่เพียงสะท้อนโค้ด' } },
  { id: 'release-radar', title: 'อ่าน release notes ให้เจอสิ่งที่กระทบโปรเจกต์เรา', summary: 'ตัวอย่างการอ่าน breaking changes และวางแผนย้ายเวอร์ชันโดยมีทางย้อนกลับ', category: 'Releases', type: 'แนวปฏิบัติ', source: 'Release Desk · สมมติ', time: '05:20', read: 4, tags: ['Python', 'Releases'], art: 'release', why: 'การอัปเดตควรมีเหตุผลจากงานที่ต้องใช้และผลกระทบที่ตรวจได้', audience: 'ผู้ดูแล dependency และทีม fullstack', technical: { impact: 'ตัวอย่างแพ็กเกจสมมติ Flowbase 2.0-demo เปลี่ยนโครงสร้าง error จากข้อความเป็น object', steps: ['ตรวจรุ่นปัจจุบันและรายการ API ที่ใช้', 'เปรียบเทียบสัญญา error เดิมกับใหม่', 'ทดลองบน branch แยกและตรวจ error path'], caveat: 'ชื่อแพ็กเกจและเวอร์ชันเป็นข้อมูลจำลอง อย่าใช้เป็นคู่มือ migration จริง' } },
];
export type ReviewStatus = 'pending' | 'published' | 'excluded' | 'rejected' | 'withdrawn';
export type QueueItem = { id: string; title: string; source: string; category: string; status: ReviewStatus; reason: string; safe: boolean; official: boolean; draft: string; original: string };
export const initialQueue: QueueItem[] = [
  { id: 'q1', title: 'Context Kit เพิ่มตัวช่วยตรวจไฟล์ก่อนส่งเข้าโมเดล', source: 'Official Demo Feed', category: 'Releases', status: 'pending', reason: 'ผ่านกฎคัดเลือก · รออนุมัติในโหมด Manual', safe: true, official: true, draft: 'ร่างจำลอง: Context Kit เพิ่มรายการไฟล์ให้ผู้ใช้ตรวจและตัดข้อมูลที่ไม่เกี่ยวข้องก่อนเริ่มงาน', original: 'ต้นฉบับจำลอง: Version 0.5-demo introduces a file preview. No performance claims. วันที่ตัวอย่าง 20 ก.ย. 2026' },
  { id: 'q2', title: 'โมเดลใหม่อ้างว่าลดต้นทุนได้อย่างก้าวกระโดด', source: 'Community Demo', category: 'งานวิจัย', status: 'pending', reason: 'แหล่งข้อมูลขัดแย้ง · ข้อกล่าวอ้างยังไม่มีหลักฐาน', safe: false, official: false, draft: 'ร่างจำลองถูกพักไว้ เพราะแหล่งข้อมูลให้รายละเอียดผลทดสอบไม่ตรงกัน', original: 'ต้นฉบับจำลอง A อ้างผลลัพธ์สูง แต่ต้นฉบับ B ใช้เงื่อนไขคนละชุด จึงยังเปรียบเทียบไม่ได้' },
  { id: 'q3', title: 'ทีมเล็กจะเริ่มใช้ AI ในงานประจำอย่างไร', source: 'Community Demo', category: 'มุมมอง', status: 'pending', reason: 'ความคิดเห็น · ต้องให้บรรณาธิการตรวจ', safe: true, official: false, draft: 'ร่างความคิดเห็นจำลอง: เริ่มด้วยงานขอบเขตเล็กและจุดตรวจที่ชัดเจน', original: 'ต้นฉบับความคิดเห็นสมมติ ไม่มีการอ้างคำพูดของบุคคลจริง' },
  { id: 'q4', title: 'Context Kit เพิ่มตัวช่วยตรวจไฟล์ (รายการซ้ำ)', source: 'Community Demo', category: 'Releases', status: 'excluded', reason: 'เหตุการณ์ซ้ำกับ q1 · รวมเข้าข่าวหลัก', safe: false, official: false, draft: 'ไม่สร้างร่างซ้ำ', original: 'ข้อมูลจำลองที่อ้างเหตุการณ์เดียวกับ Official Demo Feed' },
  { id: 'q5', title: 'บทความไม่ระบุวันที่และมีคำสั่งแฝง', source: 'Unknown Demo', category: 'เครื่องมือ', status: 'pending', reason: 'ไม่ทราบวันที่ · พบคำสั่งแฝงในแหล่งข้อมูล', safe: false, official: false, draft: 'พักร่างเพื่อให้ผู้ดูแลตรวจแหล่งข้อมูล', original: 'ตัวอย่างอันตรายจำลองถูกแสดงเป็นข้อความเท่านั้น ระบบต้นแบบไม่มีเครื่องมือให้ข่าวเรียกใช้' },
];
export const statusLabels: Record<ReviewStatus, string> = { pending: 'รอตรวจ', published: 'เผยแพร่จำลอง', excluded: 'ตัดออก', rejected: 'ปฏิเสธ', withdrawn: 'ถอนเผยแพร่' };
export type Mode = 'Manual' | 'Hybrid' | 'Auto';
export function evaluate(item: QueueItem, mode: Mode, stopped: boolean, keyword: string) {
  if (['rejected', 'withdrawn', 'excluded', 'published'].includes(item.status)) return 'คงสถานะเดิม';
  if (keyword.trim() && !`${item.title} ${item.draft}`.toLowerCase().includes(keyword.trim().toLowerCase())) return 'ตัดออก · ไม่ตรงคำสำคัญ';
  if (!item.safe) return `รอตรวจ · ${item.reason}`;
  if (stopped || mode === 'Manual') return 'รอตรวจ · Manual / หยุด Auto';
  if (mode === 'Hybrid' && !item.official) return 'รอตรวจ · กฎ Community เป็น Manual';
  return 'ผ่าน · พร้อมเผยแพร่จำลอง';
}
